sonar.projectKey=MuscleCodder06_PRJ301_ASSIGNMENT_HE200547
sonar.organization=musclecodder06

# Thư mục chứa mã nguồn Java
sonar.sources=src/java,web
sonar.java.binaries=build
sonar.sourceEncoding=UTF-8
